name: Linux-QEMU
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build-i686-windows:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        uses: ConorMacBride/install-package@v1
        with:
          apt: >
            meson
            binutils-mips-linux-gnu
            ninja-build
            bsdmainutils
            build-essential
            libaudiofile-dev
            binutils-djgpp
            binutils-mingw-w64
            libdigest-sha-perl
            mingw-w64-tools
            libsdl2-dev
            libusb-1.0-0-dev
            gcc-mingw-w64
            g++-mingw-w64-i686
            g++-mingw-w64
            g++-10-multilib
            gcc-10-multilib
            gcc-mingw-w64-x86-64-win32-runtime
            gcc-mingw-w64-i686
            mingw-w64-x86-64-dev
            mingw-w64-i686-dev
            mingw-w64-common
            libx11-dev
            bison
            diffutils
            flex
            make
            sed
            libglib2.0-dev
            libfdt-dev
            libpixman-1-dev
            ninja-build
            zlib1g-dev
            libcapstone-dev
            libslirp-dev
            pkgconf
            python3
      - name: Build qemu
        run: |
          wget --no-check-certificate https://download.qemu.org/qemu-8.2.1.tar.xz
          tar xfv qemu-8.2.1.tar.xz
          cd qemu-8.2.1
          rsync -r ../qemu-0/hw/3dfx ./hw/
          rsync -r ../qemu-1/hw/mesa ./hw/
          patch -p0 -i ../00-qemu82x-mesa-glide.patch
          cp -f ../vl.c ./system/vl.c
          mkdir ../build && cd ../build
          ../qemu-8.2.1/configure --disable-werror --target-list=i386-softmmu --enable-kvm --enable-sdl --disable-capstone --enable-slirp      
          make


      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: qemu-artifacts
          path: ./build/
